### ISSUE TITLE
Are lines supposed to be jagged?

### ISSUE THREAD

**Issue by jgiovanettiatventera** [lkcampbell/brackets-indent-guides#23] opened 2016-03-18 22:33 UTC
Hi Lance,

Are the indent guides supposed to be jagged like this?

![Jagged lines](https://dl.dropboxusercontent.com/u/26850708/jagged-lines.png)

Thanks
Justin

**Comment by lkcampbell** [comment] 2016-03-19 03:46
@jgiovanettiatventera no, that's not the way they should look.

Can you give me more information or send me a simple example file that causes this problem?

**Comment by jgiovanettiatventera** [comment] 2016-03-21 18:05
Hey Lance,

There’s no file I can send you, it’s not a file specific issue. It views like that, on all files. I suspect it has something to do with a pixel glitch at a specific resolution or some hardware issue. I don’t know. Here’s the specs of my computer, if that helps:

Windows 7 Enterprise
Intel Core i7-4610 CPU @ 3.00GHz
Memory: 16.0 GB
64-bit Operating System

Display is set to default size, for the text and icons
1920x1080

If I get time, I can create a video screen capture the issue, if that helps.

Thanks
Justin

**Comment by lkcampbell** [comment] 2016-03-31 18:43
@jgiovanettiatventera this extension simply puts an svg background right before an appropriate space or tab character. These screenshots you sent make it look like the white space character printing is off for some reason.

Can you install the `Show Whitespace` extension and see if the space characters are jagged as well?

Also, try disabling all extensions except for `Indent Guides` and see if there is still a problem.

Also, try resizing the window, changing the font size, changing the theme, turning word wrap on and off, playing around with code folding (maybe turn it on and off), or anything else you can think of that might affect where the white space characters fall on the editor window. Something must be affecting the rendering.

**Comment by jgiovanettiatventera** [comment] 2016-04-05 20:38
Hey Lance,

Here's a screenshot using the Show Whitespace extension. I'll play around with testing your other suggestions. Thanks

![Jagged lines with white space showing](https://dl.dropboxusercontent.com/u/26850708/with-white-space.png)

**Comment by jgiovanettiatventera** [comment] 2016-04-05 20:55
Just tried all of your suggestions, with no luck. No biggie, maybe I'll try completely uninstalling it.

**Comment by lkcampbell** [comment] 2016-04-06 14:26
@jgiovanettiatventera it doesn't specifically look like an indent guide problem. I can see from your picture that the start of the line is being pushed in. Also, it only seems to occur after certain comments statements like `<!-- Advanced Search Panel: END -->`. I am guessing it is some sort of core Brackets problem if it doesn't go away after you disable all extensions except indent guides.

Can you send me a copy of this html file? I will see if i can reproduce the problem so we can file the bug in the core code.

**Comment by jgiovanettiatventera** [comment] 2016-04-07 04:37
Thanks Lance. Here you go: https://dl.dropboxusercontent.com/u/26850708/store-search.html

**Comment by lkcampbell** [comment] 2016-04-07 14:08
@jgiovanettiatventera sorry I still can't reproduce the problem.

Does it only occur after those closing comments? Is there anything special about the comments?

And you already tried removing all the extensions and seeing if the problem went away?

**Comment by jgiovanettiatventera** [comment] 2016-04-08 01:11
Hey Lance,

Yea, I knew that file wouldn’t really help. The file or how Brackets interacts with the file is NOT the culprit. It must have to do with something with my system. Maybe it’s some weird local setting, like…. Maybe it’s a BOM character being inserted, maybe a CRLF issue, character encoding glitch… who knows. 

I’m going to completely uninstall/reinstall Brackets. I’ll let you know what happens.

Question… has no one written a hex viewer extension for Brackets? Not sure if you know of a way to view hex using Brackets. I know Brackets has trouble opening anything that isn’t UTF8, but detection of UTF8 is not cut and dry.


Thanks
Justin

**Comment by lkcampbell** [comment] 2016-04-08 14:28
@jgiovanettiatventera I don't know of any hex viewer extensions for Brackets but you might want to ask on the dev group:

https://groups.google.com/forum/#!forum/brackets-dev

A hidden character on the end of those comment lines occurred to me as well since I have seen similar problems occur in the past. Unfortunately, without a reproduction of the problem on my machine I can't confirm this.

I'm going to close this bug as `invalid` since it doesn't seem to be a problem with the `Indent Guides` extension. If you figure out the problem, let me know, I am interested in what is causing it.

**Closed by lkcampbell** 2016-04-08 14:28 UTC
Labels: invalid

**Comment by jgiovanettiatventera** [comment] 2016-04-11 16:26
I found the problem. It was being caused by the “Indent soft wrapped lines” extension. I don’t know why, when I first disabled the extension that it didn’t remedy the issue, but this time it did.

Also just saw that the extension is no longer supported, since the feature is implemented already in Brackets. 
https://github.com/scriptin/brackets-indent-softwraps

:-]

**Comment by lkcampbell** [comment] 2016-04-13 13:57
@jgiovanettiatventera yes, that extension and the new feature both cause problems for this extension because they are based on a CodeMirror CSS hack that gives the illusion of white space where no white space actually exists.

See Issue https://github.com/lkcampbell/brackets-indent-guides/issues/22 for more information.

**Comment by lkcampbell** [comment] 2016-04-13 14:02
Changing category to duplicate for Issue https://github.com/lkcampbell/brackets-indent-guides/issues/22.
